### ISSUE TITLE
Why removed from npm?

### ISSUE THREAD

**Issue by ahultgren** [azer/virtual-html#11]

**Comment by yoshuawuyts** [comment]
Hey, I'm currently in the process of getting this package [back from npm](https://github.com/npm/security-holder). It was unpublished yesterday by one of the maintainers. I reckon it'll be back in a day or so. Thanks for sticking along!

**Comment by ahultgren** [comment]
Ah, at first I thought this wasn't azer's deed, but ofc it was. I'm so tired of this mess...

**Comment by yoshuawuyts** [comment]
npm finally came back to me; `virtual-html` was republished as `v2.0.0`. Cheers!
