### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by ahultgren** [azer/virtual-html#12]
I ran into some issues with parsing inline svg, and it turned out to be a two-fold problem:
1. apparently, SVG elements must be created using `virtual-dom/virtual-hyperscript/svg.js` (to set `properties.attributes`)
2. `htmltree` seems to convert all attributes to lowercase

I wrote a [quick fix](https://github.com/ahultgren/virtual-html/blob/master/index.js#L61-L65) for the first issue which solves my particular case. But there must be a better way than matching [73 elements](https://developer.mozilla.org/en-US/docs/Web/SVG/Element) by name?

As for the second issue I suppose an option to not downcase attributes would be needed in both `virtual-dom` and `htmltree` (I guess there's a legitimate need for downcasing attributes)? My temporary fix [looks like this](https://github.com/ahultgren/virtual-html/blob/master/index.js#L55-L56) but that is also not sustainable.

What do you think?

**Comment by yoshuawuyts** [comment]
Thanks for opening this issue! Fixes are def welcome - feel free to put in a PR! But to be fair, I think people should be migrating to [hyperx](https://github.com/substack/hyperx) as it's better maintained, and bugs such as the ones you're outlying here have already been fixed. Cheers!

**Comment by ahultgren** [comment]
Interesting, I've never heard of it but it does look more up-to-date. This is the most starred repo listed by virtual-dom though... Guess they should update their links if hyperx is the new thing.

**Comment by yoshuawuyts** [comment]
I recommend folks use https://github.com/shama/bel instead of this package; we've been working hard on it for the past two years to make sure it has all the features you could want to write inline HTML. Hope it's good; closing for now!
