### ISSUE TITLE
ARIA attributes not handled properly

### ISSUE THREAD

**Issue by danielnixon** [azer/virtual-html#13]
ARIA attributes need to be set in `properties.attributes`:

```
var ariaExample = new VNode('div', { attributes: { "aria-checked": "true" }})
```

So in `function vnode (parent)`, below `attributes.dataset = createDataSet(attributes)` you probably want a `attributes.attributes = createAttributes(attributes)` where `createAttributes` looks something like this:

```
function createAttributes (props) {
  var attributes;
  var key;

  for (key in props) {
    if (key.slice(0, 5) == 'aria-') {
      attributes || (attributes = {});
      attributes[key] = props[key];
    }
  }

  return attributes;
}
```

See https://github.com/Matt-Esch/virtual-dom/blob/dcb8a14e96a5f78619510071fd39a5df52d381b7/docs/vnode.md#aria-attributes

**Comment by yoshuawuyts** [comment]
PR welcome, though I recommend you use [hyperx](https://github.com/substack/hyperx) - cheers!

**Comment by yoshuawuyts** [comment]
I recommend folks use https://github.com/shama/bel instead of this package; we've been working hard on it for the past two years to make sure it has all the features you could want to write inline HTML. Hope it's good; closing for now!
