### ISSUE TITLE
`npm test` fails with `Cannot find module 'ansi-codes'`

### ISSUE THREAD

**Issue by stucox** [azer/virtual-html#14]
Looks like this is because [`ansi-codes`](https://www.npmjs.com/package/ansi-codes) has been removed from NPM (which is used by `style-format`, which is used by `prova`).

@azer has fixed this on HEAD at https://github.com/azer/prova by providing his own copies of [`style-format`](https://github.com/azer/style-format) and [`ansi-codes`](https://github.com/azer/ansi-codes), but this doesn’t seem to be in a release on NPM yet.

**Comment by azer** [comment]
@stucox I think @yoshuawuyts isn't working actively on this repo. And I only publish to Github, not NPM. As an option, you can simply change "prova" to "tape" and run the tests with tape. It'll work for you.

**Comment by yoshuawuyts** [comment]
I recommend folks use https://github.com/shama/bel instead of this package; we've been working hard on it for the past two years to make sure it has all the features you could want to write inline HTML. Hope it's good; closing for now!
